{% set name = "python-geohash" %}
{% set version = "0.9.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz"
  sha256: "b5dfa7606aaf5bd1b4575a06b594a89bf557056edbac4208fcb42622bc0464f6"

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
    - setuptools
  run:
    - python

about:
  home: "https://github.com/hkwi/python-geohash"
  license: Apache-2.0
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE-2.0.txt'
  summary: "Fast, accurate python geohashing library"

extra:
  recipe-maintainers:
    - ceholden
